import type { HomepageSection } from "./homepage-management.types";

export const STORAGE_KEY = "athletica.homepage.interaction.v1";

export const SECTION_TYPES: { name: string; copy: string }[] = [
  { name: "Hero Banner", copy: "Large promotional hero with image, copy and CTA." },
  { name: "Category Grid", copy: "Display category cards and category links." },
  { name: "Product Slider", copy: "Horizontal featured product presentation." },
  { name: "Promo Banner", copy: "Marketing banner with promotional copy." },
  { name: "Product Carousel", copy: "Scrollable product collection." },
  { name: "Brand Slider", copy: "Horizontal brand showcase." },
  { name: "Product Grid", copy: "Responsive product grid." },
  { name: "Newsletter", copy: "Email capture and promotional signup." },
  { name: "Feature List", copy: "Benefits/features presented as a list." },
  { name: "Instagram Feed", copy: "Social media content grid." },
];

export const IMAGE_CHOICES = [
  "Hero — football athlete",
  "Performance — dark athlete",
  "Boot collection",
  "New arrivals",
  "Training collection",
  "Season sale",
];

export const DEFAULT_SECTIONS: HomepageSection[] = [
  {
    id: "section_hero_01",
    name: "Hero Banner",
    desc: "Elevate your game",
    type: "Hero Banner",
    active: true,
    views: "112,842",
    ctr: "14.6%",
    title: "Elevate your game",
    subtitle: "Premium gear for every athlete",
    buttonText: "Shop Now",
    linkType: "Category",
    linkValue: "Football Boots",
    spark: [4, 7, 5, 9, 13, 18, 11, 8],
  },
  {
    id: "section_category_02",
    name: "Shop by Category",
    desc: "Browse top categories",
    type: "Category Grid",
    active: true,
    views: "86,421",
    ctr: "11.2%",
    spark: [5, 7, 8, 7, 11, 13, 12, 10],
  },
  {
    id: "section_featured_03",
    name: "Featured Products",
    desc: "Top picks for you",
    type: "Product Slider",
    active: true,
    views: "62,315",
    ctr: "9.8%",
    spark: [3, 4, 7, 6, 8, 12, 9, 7],
  },
  {
    id: "section_performance_04",
    name: "Performance Collection",
    desc: "Engineered for greatness",
    type: "Promo Banner",
    active: true,
    views: "45,128",
    ctr: "10.1%",
    spark: [5, 9, 7, 8, 10, 14, 11, 8],
  },
  {
    id: "section_arrivals_05",
    name: "New Arrivals",
    desc: "The latest gear",
    type: "Product Carousel",
    active: true,
    views: "38,642",
    ctr: "8.6%",
    spark: [3, 5, 4, 6, 9, 12, 7, 5],
  },
  {
    id: "section_brands_06",
    name: "Top Brands",
    desc: "Trusted by athletes",
    type: "Brand Slider",
    active: true,
    views: "28,421",
    ctr: "6.3%",
    spark: [6, 7, 6, 8, 7, 9, 8, 10],
  },
  {
    id: "section_choice_07",
    name: "Athletes Choice",
    desc: "Gear used by pros",
    type: "Promo Banner",
    active: true,
    views: "24,842",
    ctr: "9.2%",
    spark: [4, 6, 5, 8, 10, 12, 8, 6],
  },
  {
    id: "section_best_08",
    name: "Best Sellers",
    desc: "Customer favorites",
    type: "Product Grid",
    active: true,
    views: "31,763",
    ctr: "7.1%",
    spark: [3, 5, 6, 5, 7, 10, 9, 7],
  },
  {
    id: "section_newsletter_09",
    name: "Newsletter Signup",
    desc: "Join for exclusive offers",
    type: "Newsletter",
    active: true,
    views: "18,642",
    ctr: "32.8%",
    spark: [4, 5, 5, 8, 7, 11, 9, 8],
  },
  {
    id: "section_why_10",
    name: "Why Athletica",
    desc: "Built for performance",
    type: "Feature List",
    active: true,
    views: "15,321",
    ctr: "—",
    spark: [],
  },
  {
    id: "section_instagram_11",
    name: "Instagram Feed",
    desc: "Follow our journey",
    type: "Instagram Feed",
    active: true,
    views: "12,842",
    ctr: "3.6%",
    spark: [2, 4, 3, 6, 5, 8, 6, 4],
  },
  {
    id: "section_sale_12",
    name: "End of Season Sale",
    desc: "Don't miss out",
    type: "Promo Banner",
    active: false,
    views: "—",
    ctr: "—",
    spark: [],
  },
];
